package com.paradisecloud.fcm.fme.model.cms;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * CoSpaceUser 实体类
 *
 * @Author yl
 * @Date 2020/3/11 10:32
 */
@Getter
@Setter
@ToString
public class CoSpaceUser
{
    
    /**
     * coSpace 唯一id
     */
    @JSONField(name = "@id")
    private String id;
    
    /**
     * 用户的XMPP ID
     */
    private String userJid;
    
    /**
     * 标识与任何coSpace没有关系的用户
     */
    private String userId;
    
    /**
     * 是否自动或者手动添加了这个cospace的用户 true 添加了这个coSpaceUser自动作为LDAP同步操作的一部分。它是不可能删除，除非通过修改同步操作的参数 false
     * 这个coSpaceUser可以通过以下方式添加API方法或使用Cisco会议App;它可以通过API修改或删除
     */
    private Boolean autoGenerated;
    
    /**
     * callLegProfile id 如果指定，将指定的调用分支配置文件与coSpace用户关联起来
     */
    private String callLegProfile;
    
    /**
     * 是否允许此用户删除cospace
     */
    private Boolean canDestroy;
    
    /**
     * 是否允许该用户添加或删除其他cospace的成员
     */
    private Boolean canAddRemoveMember;
    
    /**
     * 是否允许此用户修改cospace的名字
     */
    private Boolean canChangeName;
    
    /**
     * 是否允许此用户修改cospace的uri
     */
    private Boolean canChangeUri;
    
    /**
     * 是否允许此用户修改cospace的call id
     */
    private Boolean canChangeCallId;
    
    /**
     * 是否允许此用户修改cospace的密码
     */
    private Boolean canChangePasscode;
    
    /**
     * 是否允许此用户写入信息
     */
    private Boolean canPostMessage;
    
    /**
     * 是否允许此用户从cospace中移出自己
     */
    private Boolean canRemoveSelf;
    
    /**
     * 是否允许此用户从cospace信息板删除所有信息
     */
    private Boolean canDeleteAllMessages;
    
    /**
     * 是否允许此用户更改coSpace的“非成员访问允许设置”（2.3版本）
     */
    private Boolean canChangeNonMemberAccessAllowed;
}
